# Generated by Django 4.0.9 on 2023-02-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('price', models.PositiveIntegerField()),
                ('make', models.CharField(choices=[('GER', 'German'), ('JPN', 'Japan'), ('USA', 'USA')], default='GER', max_length=3)),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
